# Generated by Django 5.2 on 2025-10-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_org_site", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="is_completed",
        ),
        migrations.AddField(
            model_name="homework",
            name="status",
            field=models.CharField(
                choices=[
                    ("TODO", "Todo"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                default="TODO",
                max_length=200,
            ),
        ),
    ]
