# Generated by Django 5.2 on 2025-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homework_org_site", "0002_remove_homework_is_completed_homework_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TODO", "Todo"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                ],
                default="TODO",
                max_length=200,
            ),
        ),
    ]
